apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: growth-engine-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: growth-engine

  source:
    repoURL: https://github.com/equitybrix/growth-engine-gitops.git
    targetRevision: main
    path: environments/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: growth-engine-prod

  syncPolicy:
    # Manual sync for production - requires approval
    automated: null
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m

  # Production-specific settings
  revisionHistoryLimit: 10

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
